import Script from "next/script";
import { Inter } from "next/font/google";

import "node_modules/@crunchyroll/cx-web-components/dist/styles-ltr.css";

import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Script id="segment-analytics" strategy="afterInteractive">
          {`
            window.etp = window.etp || {};
            window.etp.config = {
              analytics: {
                defaultApiHost: 'api.segment.io/v1',
                writeKey: 'bmeXq8x8muZC8wdIBwH5dPnfeErtJM2r',
                fallbackLibraryHost: 'sa.etp-proto0.com/analytics.js/v1/',
                domain: 'crunchyroll',
                gtmId: 'GTM-PK7T4JG'
              }
            };
          `}
        </Script>
        <Script
          src="https://static.crunchyroll.com/analytics/segment.v5.0.0.js"
          strategy="afterInteractive"
        />

        {children}
      </body>
    </html>
  );
}
